### ISSUE TITLE
Urgent issue! 

### ISSUE THREAD

**Issue by Szechuan76** [omarkmu/krdict.py#1]
I just think if you could rework your data plots, you could actually solve the energy crisis and still make it to prom. I know this is a bit over your head, so I left a picture to help reference what I'm talking about. 
![MV5BYjMxNzBhMjYtYzAwZS00MDcyLTk5NTItNmMwM2Y2MzYxMTgyXkEyXkFqcGdeQXVyNjAwMjc0NjQ@ _V1_UX182_CR0,0,182,268_AL_](https://user-images.githubusercontent.com/91858129/135781328-11d9a5a6-c22c-4f78-be7a-6b2e33ae8b23.jpg)

**Comment by omarkmu** [comment]
Fixed in release 1.0.0.
